services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      ENV: LOCAL
      HOST: '0.0.0.0'
      PORT: 3000
