# fly.toml app configuration file generated for mtg-rules-chatgpt-plugin on 2023-06-09T20:29:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mtg-rules-chatgpt-plugin"
primary_region = "lax"

[build]
  dockerfile = "docker/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
